
version: 2

models:
  - name: raw_supply_chain
    schema: main
    meta:
      external_locations: "data/raw/{name}.csv"
    tables:
      - name: train
        description: "Historical sales demand (Kaggle data)"
      - name: mock_inventory_snapshot
        description: "Current on-hand inventory"
      - name: mock_supply_orders
        description: "Open and closed POs"        
        data_tests:
          - unique
          - not_null